Milestone 2 : Process data by associaton
ABDULALI3468/Rails-blog-App pull request #2
Opened 2022-09-16 14:23 UTC by ABDULALI3468

> ## what I did ♻️
> > In this project's milestone, I Set up associations between models.
> 
> ## Project requirements 📗
> ### Create models
> * Create model classes for all entities as shown.
> * Set up associations between models.
> 
> ### Use models to insert data
> * Familiarize yourself with ['rails c' command](https://guides.rubyonrails.org/command_line.html#bin-rails-console).
> * Open rails console for your project.
> * Create at least one user by running the following code:
>   ```ruby
>      first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
>      second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
>   ```
> * Create at least 4 posts written by one of the users you created by running the following code:
>   ```ruby
>      first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
>   ```
> * Create at least 6 posts comments for one of the posts you created by running the following code:
>   ```ruby
>      Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
>   ```
> * Use other CRUD methods to find, update and delete entities.
> 
> ### Create custom methods
> Your models should include some additional methods.
> 
> * Users
>   
>   * A method that returns the 3 most recent posts for a given user.
> * Posts
>   
>   * A method that updates the posts counter for a user.
>   * A method that returns the 5 most recent comments for a given post.
> * Comments
>   
>   * A method that updates the comments counter for a post.
> * Likes
>   
>   * A method that updates the likes counter for a post.
> * Go to `rails c` and check if your methods are working.

2022-09-16 15:14 UTC, FrederickMih reviewed
Hi @ABDULALI3468, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that does contain a descriptive README.md file.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-16 16:04 UTC, Rustamxon7 requested changes
Hello @ABDULALI3468, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 16:04 UTC, Rustamxon7 commented on app/models/post.rb
> +  def increment_posts_counter
- [ ] I is good practice if you put the `increment_posts_counter` after `private`. 


[More info...](https://guides.rubyonrails.org/active_record_callbacks.html#:~:text=before_validation%20%3Aensure_login_has_a_value-,private,-def%20ensure_login_has_a_value%0A%20%20%20%20%20%20if)

2022-09-17 08:13 UTC, medaminedev66 approved these changes
Hi @ABDULALI3468 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- There are no linters errors.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 08:13 UTC, medaminedev66 commented on app/models/comment.rb
> +  def increment_comments_counter
[OPTIONAL] Since you call `increment_comments_counter` after create, it would be preferable to add it after `private`, as was stated by the prior reviewer in the previous review.

2022-09-17 08:13 UTC, medaminedev66 commented on app/models/like.rb
> +  def increment_likes_counter
[OPTIONAL] Since you call `increment_likes_counter` after create, it would be preferable to add it after "private," as was stated by the prior reviewer in the previous review.

2022-09-17 08:16 UTC, ABDULALI3468 commented on app/models/like.rb
> +  def increment_likes_counter
@medaminedev66 thanks mate.

2022-09-17 09:38 UTC, merged